/// Flutter icons MyApp1
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyApp1
///      fonts:
///       - asset: fonts/MyApp1.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyApp1 {
  MyApp1._();

  static const _kFontFam = 'MyApp1';
  static const String? _kFontPkg = null;

  static const IconData stopwatch_1 =
      IconData(0xf2f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
